<?php

/*
 * IMPORTANT: This file is generated by sfBehatPlugin - edit at your own peril.
 * It is recommended to regenerate this file in the future when you upgrade to a 
 * newer version of sfBehatPlugin. Consider adding your own hooks to a user 
 * hooks.php under test/features instead of editing this one.
 */

/*
 * This file is part of the sfBehatPlugin package.
 * (c) 2010 Konstantin Kudryashov <ever.zet@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

$hooks->beforeSuite(function($event) {
    $app = basename(dirname(__DIR__));
    require_once(__DIR__ . '/../../../bootstrap/functional.php');
});

